language: php

php:
  - 7.2.16

services:
  - mysql

cache:
  directories:
    - node_modules
    - vendor

# addons:
#   chrome: stable
before_script:
  - cp .env.travis .env
  - mysql -e 'create database testing;'
  - composer self-update
  - composer install --no-interaction
  - php artisan key:generate
  - php artisan migrate --seed

script:
  - vendor/bin/phpunit
